# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:            Slowly Sipping
email:            hello@slowlysipping.com
description:      Travel stories and inspiration from a down-to-earth girl in tech
baseurl:          '' # The subpath of your site, e.g. /blog
url:              'https://slowlysipping.com' # The base hostname & protocol for your site
github_username:
twitter_username:
instagram: slowlysipping

markdown:  kramdown
permalink: pretty
paginate:  12
sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# SEO settings
title: Slowly Sipping
description: Travel stories and inspiration from a down-to-earth girl in tech
url: "https://slowlysipping.com"
twitter_username:
default_img:

# Profile settings
name: slowlysipping
profile_img:
profile:
social:
  github:
  instagram: instagram


# Authors
authors:
  ahmad:
    name:             a person
    bio:              doing things people do
    gravatar:         https://s.gravatar.com/avatar/f83141edd9e6339e678648596a403fd5?s=150
    email:
    website:
    github_username:
    twitter_username: