# Site settings
email: hello@slowlysipping.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: UA-97406907-1

# SEO settings
title: Slowly Sipping
description: A lifestyle and travel blog
url: ""
twitter_username: 
default_img: '/sipping.jpg'

# Profile settings
name: meow
profile_img: /banner.jpg
profile: Slowly Sipping is a blog, travelogue, notebook, et cetera.
social:

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
